export const environment = {
  production: true,
  backend_end_point: 'https://kiranamysore.com/',
  port_number: '8000',
  userDetails: 'api/v1/userDetails/',
  order: "api/v1/vendor/order/",
  orders: 'api/v1/vendor/order/?order=listall',
  retailers: 'api/v1/vendors/',
  forgotPassword: 'api/v1/forgot_password/',
  updatePassword: 'api/v1/update_password/',
  products: 'api/v1/products/',
  imageUpload: 'api/v1/imageUpload/',
  signUpURL: 'user/signUp/',
  loginURL: 'login/',
  tokenURL: 'api/token/',
  refreshURL: 'api/token/refresh',
  inviteURL: "api/v1/vendor_request/",
  inviteResponseURL: "api/v1/vendor_registration/",
  feedbackURL:"api/v1/ratings/",
  resetPassURL: 'api/v1/update_password/',
  notification: 'api/v1/vendor/order/',
  disableVariant: "api/v1/disabled_products/",
  blockVendorURL: 'api/v1/block_vendor/',
  hideVendorURL: 'api/v1/hide_vendor/',
  readNotification: 'api/v1/read_notification',
  readAllNotifications: 'api/v1/read_all'
};
